services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_cluster
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # Essential settings for replication later
    command: 
      - "postgres"
      - "-c"
      - "wal_level=replica"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
      - "-c"
      - "hot_standby=on"
